        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 28 14:57:16 2015
        MODULE CONVERT2SOL__genmod
          INTERFACE 
            SUBROUTINE CONVERT2SOL
            END SUBROUTINE CONVERT2SOL
          END INTERFACE 
        END MODULE CONVERT2SOL__genmod
