        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 28 14:57:15 2015
        MODULE DEFINE_ROOTGROWTH__genmod
          INTERFACE 
            SUBROUTINE DEFINE_ROOTGROWTH(SOIL_DEPTH)
              REAL(KIND=4) :: SOIL_DEPTH
            END SUBROUTINE DEFINE_ROOTGROWTH
          END INTERFACE 
        END MODULE DEFINE_ROOTGROWTH__genmod
