        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 28 14:57:15 2015
        MODULE ESTIMATE_SLNI__genmod
          INTERFACE 
            SUBROUTINE ESTIMATE_SLNI(SOIL_DEPTH)
              REAL(KIND=4) :: SOIL_DEPTH
            END SUBROUTINE ESTIMATE_SLNI
          END INTERFACE 
        END MODULE ESTIMATE_SLNI__genmod
