        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 28 14:57:14 2015
        MODULE FIND_COUNTRY_ACRONYM__genmod
          INTERFACE 
            SUBROUTINE FIND_COUNTRY_ACRONYM(INTEGER_N3,OUT_STR2,OUT_STR3&
     &)
              INTEGER(KIND=4) :: INTEGER_N3
              CHARACTER(LEN=2) :: OUT_STR2
              CHARACTER(LEN=3) :: OUT_STR3
            END SUBROUTINE FIND_COUNTRY_ACRONYM
          END INTERFACE 
        END MODULE FIND_COUNTRY_ACRONYM__genmod
