        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 28 14:57:17 2015
        MODULE FIND_HC_PROFILE__genmod
          INTERFACE 
            SUBROUTINE FIND_HC_PROFILE(ROW_I,COL_I)
              INTEGER(KIND=4) :: ROW_I
              INTEGER(KIND=4) :: COL_I
            END SUBROUTINE FIND_HC_PROFILE
          END INTERFACE 
        END MODULE FIND_HC_PROFILE__genmod
