        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 28 14:57:16 2015
        MODULE INITIALIZE_VAR__genmod
          INTERFACE 
            SUBROUTINE INITIALIZE_VAR
            END SUBROUTINE INITIALIZE_VAR
          END INTERFACE 
        END MODULE INITIALIZE_VAR__genmod
