        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 28 14:57:12 2015
        MODULE INT2CHAR__genmod
          INTERFACE 
            SUBROUTINE INT2CHAR(N,SZ,STR)
              INTEGER(KIND=4), INTENT(IN) :: SZ
              INTEGER(KIND=4), INTENT(IN) :: N
              CHARACTER(LEN=SZ), INTENT(OUT) :: STR
            END SUBROUTINE INT2CHAR
          END INTERFACE 
        END MODULE INT2CHAR__genmod
