        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 28 14:57:17 2015
        MODULE MAKE_SOIL_ID__genmod
          INTERFACE 
            SUBROUTINE MAKE_SOIL_ID(CNTRY_STR,S_ID)
              CHARACTER(LEN=2) :: CNTRY_STR
              CHARACTER(LEN=10) :: S_ID
            END SUBROUTINE MAKE_SOIL_ID
          END INTERFACE 
        END MODULE MAKE_SOIL_ID__genmod
