        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 28 14:57:16 2015
        MODULE READ_INPUT_LIST__genmod
          INTERFACE 
            SUBROUTINE READ_INPUT_LIST(FPARAM)
              CHARACTER(LEN=90) :: FPARAM
            END SUBROUTINE READ_INPUT_LIST
          END INTERFACE 
        END MODULE READ_INPUT_LIST__genmod
