        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 28 14:57:11 2015
        MODULE WHAT_TEX_4HC__genmod
          INTERFACE 
            FUNCTION WHAT_TEX_4HC(SAND,CLAY)
              REAL(KIND=4), INTENT(IN) :: SAND
              REAL(KIND=4), INTENT(IN) :: CLAY
              CHARACTER(LEN=1) :: WHAT_TEX_4HC
            END FUNCTION WHAT_TEX_4HC
          END INTERFACE 
        END MODULE WHAT_TEX_4HC__genmod
