        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 28 14:57:12 2015
        MODULE WHAT_TEXTURE__genmod
          INTERFACE 
            FUNCTION WHAT_TEXTURE(SAND,CLAY)
              REAL(KIND=4), INTENT(IN) :: SAND
              REAL(KIND=4), INTENT(IN) :: CLAY
              CHARACTER(LEN=9) :: WHAT_TEXTURE
            END FUNCTION WHAT_TEXTURE
          END INTERFACE 
        END MODULE WHAT_TEXTURE__genmod
